# ========================================
# SpeedRunPlus (SRP) Configuration
# ========================================

# Main world names - used to teleport players back to when runs complete
main-overworld: world
main-nether: world_nether
main-end: world_the_end

# Game rule settings
game-rules:

  # Assisted triangulation
  assisted-triangulation:

    # Whether to use assisted triangulation
    use-assisted-triangulation: false

    # The triangulation strategy - specifies the triangulation algorithm and thereby the level of assistance and
    # variance during the assisted triangulation
    strategy: DETERMINISTIC

  # Speedrun world seeds
  filtered-seeds:

    # Whether to use filtered seeds or rely on random seeds
    use-filtered-seeds: false

    # Filtered seeds API
    filtered-seeds-api: https://filteredseed.com/getRandomUsedSeed/

    # Weights for each type of seed (higher number = more likely to appear)
    weights:
      MAPLESS: 1
      VILLAGE: 1
      TEMPLE: 1
      SHIPWRECK: 1
      RUINED_PORTAL: 1
      RANDOM: 1

  # Maximum number of players allowed to speedrun simultaneously
  # Used it to limit the toll on the server's resources
  max-players: 4

  # Maximum duration of a speedrun in minutes
  # Use it to limit the time a player can spend in a single run
  max-time-minutes: 120

  # Time before requests for BattleSpeedrun / Co-op are invalidated
  max-request-seconds: 30

# Prefix used for generated speedrun worlds
world-prefix:
  overworld: srp-overworld-
  nether: srp-nether-
  end: srp-end-

# Timer settings
timer:

  # The amount of time to countdown from, when starting a speedrun in seconds
  countdown-seconds: 10

# Podium configuration (solo runs exclusively)
podium:

  # Maximum number of leaderboard entries to display on the podium
  max: 10

  # The world in which the following positions are used as the podium
  world: world

  # The positions in the above world where the leaderboard entries are created as the podium
  positions:
    1:
      x: 0.5
      y: 80.5
      z: 0.5
      yaw: 90

# AFK configuration
afk:

  # Minutes before ending a speedrun due to inactivity
  timeout-minutes: 5

  # Intervals between each AFK check
  check-interval-seconds: 60

  # Minimum number of blocks the player needs to move
  # to be considered active between each AFK check
  min-distance: 1.0
